### ISSUE TITLE
SQL generated in unary function breaks MySQL

### ISSUE THREAD

**Issue by JPKramer707** [brandon-d-mckay/krauter#2]
Shhhh! Don't tell anyone, but I'm a front-end developer masquerading as a full-stack developer. As such, I'm not producing kosher SQL, as you will see in a moment.

Nevertheless, I think this should work yet it doesn't.

I have a query that grabs a list of nodes.

```sql
		SELECT
			Node.*
		FROM
			Node
		LEFT JOIN
			Junction
				ON Node.id = Junction.child_node_id
		WHERE
			Junction.node_id IS NULL;
```

Using that list of nodes, I generate a second query that grabs all the child nodes of the original list.

```sql
		SELECT
            Junction.node_id as parent_id,
			Node.*
		FROM
			Junction
		LEFT JOIN
			Node
				ON Junction.child_node_id = Node.id
		WHERE
        	Junction.node_id = 1 OR Junction.node_id = 10 OR Junction.node_id = 11 OR Junction.node_id = 13 OR Junction.node_id = 16 OR Junction.node_id = 17 OR Junction.node_id = 19
```

Both of these queries run just fine. I can paste them into the MySQL console, run them, and retrieve results. No problem!

But, the second query, when I run it through Krauter, I get this error from MySQL:

```
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''\n\t\t\tSELECT\n\t\t\t\tJunction.node_id as parent_id,\n\t\t\t\tNode.*\n\t\t\tF' at line 1
```

As far as I can see, the generated query is identical to the static query above. Yet, there must be some difference, why the error?

Here's my Krauter code...

```javascript
router.get('/all',
	`
		SELECT
			Node.*
		FROM
			Node
		LEFT JOIN
			Junction
				ON Node.id = Junction.child_node_id
		WHERE
			Junction.node_id IS NULL;
	`,
	({ req, res, data }) => {
		req.childNodeSQL = `
			SELECT
				Junction.node_id as parent_id,
				Node.*
			FROM
				Junction
			LEFT JOIN
				Node
					ON Junction.child_node_id = Node.id
			WHERE
				` + 'Junction.node_id = ' + pluck('id', data).join(' OR Junction.node_id = ');
		req.childNodes = data;
		return data;
	},
	":childNodeSQL:"
);
```

I appreciate your help!

**Comment by brandon-d-mckay** [comment]
When you denote a property of the `req` object in surrounding colons, it's interpreted as a value that should be parameterized with the query (to prevent SQL injection... which is actually kind of what you're unintentionally doing :smiley:). In the case of the *mysql* npm package, it parameterizes a value by first converting it to a string (if it isn't one already) and then inserting it into the query surrounded by apostrophes (after escaping any apostrophes that were originally in the string itself). 

So you would expect your resulting query to be this:
`SELECT * FROM table`

But what you actually get is this:
`'SELECT * FROM table'`

However, from seeing what you were trying to do in your code, it's pretty apparent that there needs to be a way to easily execute SQL query strings that are generated using method calls etc. I'm working on this now and will have this new feature released within the next couple of days.

Also, thanks for posting here and trying out the package!

**Comment by JPKramer707** [comment]
Thank you. This makes sense.

I have since solved my particular problem by writing some cleaner SQL, but I also see how this is probably going to come up again in the future.

I appreciate that you're working on it.

Also, I am a big fan of Krauter so far. Even says so in my git commit.

```
commit 2b41e3fb8fecd2d655eeba37d729bebbcaf17508
Author: JP Kramer <jpkramer707_github@mmx.st>
Date:   Sat Apr 20 16:27:24 2019 -0700

    Updated schema.
    Added route /node/0
    Added router /relation/*
    Implemented Krauter - NO REGRETS!
```

It's really cleaned up my express.js code, which was such a pain and eyesore before. So much repeated boilerplate. Bleh! Yeah, Krauter is just what I was shopping for. I appreciate your sharing it, and I look forward to the cool new stuff you'll be rolling out.

Peace!

**Comment by brandon-d-mckay** [comment]
The most recently released version has solved this issue, so now you can just do something like, `return new Query(childNodeSQL)` at the end of your last middleware function and it will execute the query and store the result to `req.data` as expected. Also, sorry for the delay in resolving the issue, let me know if you have any more questions or problems! Thanks! :smiley:
